services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    privileged: true
    networks:
      local-net:
        ipv4_address: 192.168.3.102
    tty: true

  gs1-server:
    image: glusterfs
    container_name: gs1-server
    privileged: true
    volumes:
      - ./volumes/server1:/data
    networks:
      local-net:
        ipv4_address: 192.168.3.100

  gs2-server:
    image: glusterfs
    container_name: gs2-server
    privileged: true
    volumes:
      - ./volumes/server2:/data
    networks:
      local-net:
        ipv4_address: 192.168.3.101

networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24